# Generated by Django 4.0.3 on 2022-04-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_rename_athletes_athlete'),
        ('events', '0002_rename_events_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='athletes',
            field=models.ManyToManyField(null=True, to='athletes.athlete'),
        ),
    ]
