# Generated by Django 4.0.3 on 2022-04-02 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0003_rename_year_olympic_year'),
        ('events', '0004_event_olympic_game_alter_event_athletes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('event_name', 'olympic_game')},
        ),
    ]
