# Generated by Django 4.0.3 on 2022-04-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_alter_athlete_sex'),
        ('events', '0005_alter_event_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='athletes',
            field=models.ManyToManyField(related_name='athlete_events', to='athletes.athlete'),
        ),
    ]
