# Generated by Django 4.0.3 on 2022-04-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0002_rename_medals_medal'),
        ('olympics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Olympics',
            new_name='Olympic',
        ),
    ]
