# Generated by Django 4.0.3 on 2022-04-01 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('events', '0001_initial'),
        ('olympics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='athletes.athletes')),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
                ('olympic_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympics.olympics')),
            ],
        ),
    ]
