# Generated by Django 4.0.3 on 2022-04-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0002_rename_medals_medal'),
    ]

    operations = [
        migrations.AddField(
            model_name='medal',
            name='medal_type',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], default='gold', max_length=10),
            preserve_default=False,
        ),
    ]
