# Generated by Django 4.0.3 on 2022-04-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0004_alter_medal_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='medal',
            name='athlete_age',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
