# Generated by Django 4.0.3 on 2022-04-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0005_medal_athlete_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medal',
            name='athlete_age',
            field=models.IntegerField(null=True),
        ),
    ]
