# Generated by Django 4.0.3 on 2022-04-04 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_alter_athlete_sex'),
        ('events', '0006_alter_event_athletes'),
        ('medals', '0006_alter_medal_athlete_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medal',
            name='athlete',
        ),
        migrations.AddField(
            model_name='medal',
            name='athlete',
            field=models.ManyToManyField(related_name='athlete_medals', to='athletes.athlete'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='event_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='events.event'),
        ),
    ]
