# Generated by Django 4.0.3 on 2022-04-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('medals', '0001_initial'),
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Athletes',
            new_name='Athlete',
        ),
    ]
