# Generated by Django 4.0.3 on 2022-04-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_athlete_medals_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='events_count',
            field=models.IntegerField(default=0),
        ),
    ]
